### ISSUE TITLE
Html5

### ISSUE THREAD

**Issue by augusto-salto** [pabloads/curso-html5-css3-gustavo-guanabara#1]

**Comment by KauaB** [comment]
Mano dei uma olhadinha no seu código e tem algumas coisas foras de ordens, no menu de especificações tá com a barra de rolagem e na hora de clicar nas partes do óculos Glass acontece um erro ou uma falta de código, pois a parte de câmera e de bateria não está clicável. Tem mais alguns erros de códigos mas não são importantes.
